Attribute VB_Name = "Form_Form2"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
Option Compare Database

Private Sub Command0_Click()
    'Dim pb As PoliceBlotter.PoliceBlotter
    'Dim table As Variant
    
    'pb = CreateObject("PoliceBlotterDAL.PoliceBlotter")
    
    'table = SPs.UspGetOfficerDuties(1, 5, 23).GetDataSet()
    
    'MsgBox table
End Sub
